### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: java.net.InetAddress$CachedAddresses

### ISSUE THREAD

**Issue by 0x1227** [alibaba/java-dns-cache-manipulator#190]
```java
Caused by: java.lang.ClassNotFoundException: java.net.InetAddress$CachedAddresses
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:421) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:412) ~[na:na]
	at com.alibaba.dcm.internal.InetAddressCacheUtilForNew.getConstructorOfInetAddress$CachedAddresses(InetAddressCacheUtilForNew.java:82) ~[dns-cache-manipulator-1.8.1.jar:na]
	at com.alibaba.dcm.internal.InetAddressCacheUtilForNew.newCachedAddresses(InetAddressCacheUtilForNew.java:67) ~[dns-cache-manipulator-1.8.1.jar:na]
	at com.alibaba.dcm.internal.InetAddressCacheUtilForNew.setInetAddressCache(InetAddressCacheUtilForNew.java:54) ~[dns-cache-manipulator-1.8.1.jar:na]
	at com.alibaba.dcm.DnsCacheManipulator.setDnsCache(DnsCacheManipulator.java:46) ~[dns-cache-manipulator-1.8.1.jar:na]
	... 27 common frames omitted
```

**Comment by oldratlee** [comment]
@0x1227 using java 21?

not support java 21 yet.

**Comment by casparcwang** [comment]
在jdk8u352之后java.net.InetAddress$CachedAddresses也被删除了，当前主干依然是会失败的，这个不知道官方包打算支持吗？

详见https://github.com/openjdk/jdk8u/blob/master/jdk/src/share/classes/java/net/InetAddress.java

**Comment by hanjiangjiaolong** [comment]
java17 的javafx模块化使用时就会出现这个错误

**Comment by oldratlee** [comment]
如果是模块化使用方式，要相应的参数；参见项目文档的相应说明：@hanjiangjiaolong

https://github.com/alibaba/java-dns-cache-manipulator?tab=readme-ov-file#jvm-settings-for-java-16

**Comment by hanjiangjiaolong** [comment]
[javafx.zip](https://github.com/alibaba/java-dns-cache-manipulator/files/14003676/javafx.zip)
@oldratlee  
`<profiles>
    <profile>
        <id>add-java-open-options-for-jdk16+</id>
        <activation>
            <jdk>[16,)</jdk>
        </activation>
        <properties>
            <argLine>
                --add-opens java.base/java.net=ALL-UNNAMED
                --add-opens java.base/sun.net=ALL-UNNAMED
            </argLine>
        </properties>
    </profile>
</profiles>`
我没添加jvm参数，但是我添加了profiles，但是还是有错误，可以看下demo

**Comment by oldratlee** [comment]
@hanjiangjiaolong 

- `java-dns-cache-manipulator`还没有做`Java`支持。
- 模块化应用运行如何使用添加选项可以查一下。
  - `JVM`选项添加在哪儿生效和你的运行方式相关。
  - 上面`Maven Profile`加的`JVM`选项可以对`mvn test`生效。

-------

下面简单说明一下可能有用，如果有问题你自己查一下排查吧：

`java-dns-cache-manipulator`自动模块化了，模块名是`dns.cache.manipulator`。
（我看你在`module-info.java`中已经使用了）

要添加的选项是：

```java
--add-opens java.base/java.net=dns.cache.manipulator --add-opens java.base/sun.net=dns.cache.manipulator
```

IDEA运行方式添加方式：

![image](https://github.com/alibaba/java-dns-cache-manipulator/assets/1063891/41452537-3e42-4404-a33d-b2729ded122e)

**Comment by oldratlee** [comment]
@ran222 是你说这样的。

在文档README中，也是这样说明：

https://github.com/alibaba/java-dns-cache-manipulator?tab=readme-ov-file#jvm-settings-for-java-16

前一条comment中的说明不对。
（Comment内容我也更新）
